version: 2
updates:
- package-ecosystem: gradle
  directory: "/./app"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore(deps)
- package-ecosystem: gradle
  directory: "/./maps-compose"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore(deps)
